version: 0.2

env:
  variables:
    S3_GALLERY    : "bcele-site-test-123"
    S3_TARGET     : "bcele-ci-upload-test"
    BUILD_ENV     : "prod"
    BUILD_DIR     : "dist"
    BUILD_CONTENT : "content"

phases:
  install:
    commands:
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - echo Installing nodeJs
    - sudo apt-get update -y
    - sudo apt-get install -y nodejs
    - sudo apt-get install -y apt-transport-https
    - npm install

  build:
    commands:
    - echo Creating dist and content directory
    - mkdir dist
    - mkdir ${BUILD_CONTENT}

    - echo Downloading Media From S3
    # - aws s3 cp s3://${S3_GALLERY} ./${BUILD_DIR} --recursive
    - aws s3 cp s3://${S3_GALLERY} ./${BUILD_CONTENT} --recursive

    - echo Printing out all contents of the build content folder
    - ls ./${BUILD_CONTENT} -a

    - echo Printing out all contents of this folder
    - ls  -a

    # - echo Downloading Media from S3
    # - aws s3 cp s3://brett-portfolio-image-vault . --recursive
    # - mv gallery/about about
    # - mv gallery/applications applications
    # - mv gallery/artwork artwork
    # - mv gallery/photography photography
    # - mv gallery/short-films short-films
    # - mv gallery/spatial spatial
    
    #- echo Build started
    #- npm run build

  post_build:
    commands:
    - aws s3 rm s3://${S3_TARGET} --recursive
    - echo S3 bucket is cleared

    # Works
    # - aws s3 cp ${BUILD_CONTENT}/gallery/ s3://${S3_TARGET} --acl public-read --recursive --include "*.jpg" --exclude "*.png"
    # - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
#     # - 
  discard-paths: yes
#   # base-directory: 'dist*'
  base-directory: 'content*'
