version: 0.2

env:
  variables:
    S3_BUCKET: "bcele-site-test-123"
    BUILD_ENV : "prod"
    BUILD_DIR : "dist"

phases:
  install:
    commands:
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - echo Installing nodeJs
    - sudo apt-get update -y
    - sudo apt-get install -y nodejs
    - sudo apt-get install -y apt-transport-https
    - npm install

  build:
    commands:
    - echo Current Branch
    - git branch | grep \* | cut -d ' ' -f2

    - echo Checking Out Branch - Prod
    - git checkout prod

    - echo Downloading Media From S3
    - aws s3 cp s3://bcele-site-test-123 . --recursive

    - echo Printing out all contents of this folder
    - ls -a
    
    # - echo Downloading Media from S3
    # - aws s3 cp s3://brett-portfolio-image-vault . --recursive
    # - mv gallery/about about
    # - mv gallery/applications applications
    # - mv gallery/artwork artwork
    # - mv gallery/photography photography
    # - mv gallery/short-films short-films
    # - mv gallery/spatial spatial
    
    #- echo Build started
    #- npm run build

  post_build:
    commands:
    #- aws s3 rm s3://${S3_BUCKET} --recursive
    #- echo S3 bucket is cleared
    #- aws s3 cp ${BUILD_DIR}/* s3://${S3_BUCKET} --acl public-read --recursive
    #- echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist*'